export const FETCH_ARTICLE_LIST = "FETCH_ARTICLE_LIST";
export const UPDATE_ARTICLE_LIST = "UPDATE_ARTICLE_LIST";
export const CHANGE_ARTICLE_LOAD_STATE = "CHANGE_ARTICLE_LOAD_STATE";
export const DELETE_ARRTICLE = "DELETE_ARTICLE";
export const ADD_ARTICLE = "ADD_ARTICLE";
export const UPDATE_ARTICLE_PAGE = "UPDATE_ARTICLE_PAGE";

export const FETCH_CLASSIFICATION_LIST = "FETCH_CLASSIFICATION";
export const UPDATE_CLASSIFICATION_LIST = "UPDATE_CLASSIFICATION_LIST";
export const UPDATE_CLASSIFICATION_ITEM = "UPDATE_CLASSIFICATION_ITEM";
export const DELETE_CLASSIFICATION_BY_ID = "DELETE_CLASSFICATION_BY_ID";
export const ADD_CLASSIFICATION = "ADD_CLASSIFICATION";