export const FETCH_ARTICLE_LIST = "FETCH_ARTICLE_LIST";
export const UPDATE_ARTICLE_LIST = "UPDATE_ARTICLE_LIST";
export const GET_ARTICLE_BY_ID = "GET_ARTICLE_BY_ID";
export const CHANGE_ARTICLE_LOAD_STATE = "CHANGE_ARTICLE_LOAD_STATE";