export const FETCH_ARTICLE_LIST = "FETCH_ARTICLE_LIST";
export const UPDATE_ARTICLE_LIST = "UPDATE_ARTICLE_LIST";
export const CHANGE_ARTICLE_LOAD_STATE = "CHANGE_ARTICLE_LOAD_STATE";
export const DELETE_ARRTICLE = "DELETE_ARTICLE";
export const ADD_ARTICLE = "ADD_ARTICLE";

export const FETCH_CLASSIFICATION = "FETCH_CLASSIFICATION";
export const UPDATE_CLASSIFCATION_NAME_BY_ID = "UPDATE_CLASSIFCATION_NAME_BY_ID";
export const UPDATE_CLASSFICATION_ID = "UPDATE_CLASSFICATION_ID";
export const DELETE_CLASSFICATION_BY_ID = "DELETE_CLASSFICATION_BY_ID";
